name: Pytest
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:   
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./backend
    steps:
    - name: Set up the database and backend
      run: docker compose up -d mongodb backend
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cahe: 'pip'
    - name: Install dependencies
      run: |
      working-directory: ./backend
        python -m pip install --upgrade pip
        pip install -r requirements.pip 
    - name: Unit tests
      working-directory: ./backend
      run: |
        python -m pytest -m unit
